In [7]:
import numpy as np
import pandas as pd
import joblib
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

def load_data(file_path):
    """Load the Iris dataset from a CSV file."""
    df = pd.read_csv(file_path)
    
    # Check the first few rows to determine the actual feature columns
    print(df.head())  
    
    # Assuming the dataset has an ID column, drop the first column
    df = df.iloc[:, 1:]  # Adjust index based on dataset structure

    X = df.iloc[:, :-1].values  # Feature columns (4)
    y = df.iloc[:, -1].values   # Target column (species)
    return X, y, np.unique(y)


def preprocess_data(X):
    """Standardize the feature values."""
    scaler = StandardScaler()
    X_scaled = scaler.fit_transform(X)
    return X_scaled, scaler

def train_model(X_train, y_train):
    """Train the RandomForest model."""
    clf = RandomForestClassifier(n_estimators=100, random_state=42)
    clf.fit(X_train, y_train)
    return clf

def evaluate_model(model, X_test, y_test):
    """Evaluate the model's performance."""
    y_pred = model.predict(X_test)
    accuracy = accuracy_score(y_test, y_pred)
    print(f"Model Accuracy: {accuracy:.2f}")
    print("\nClassification Report:\n", classification_report(y_test, y_pred))
    print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))

def predict_species(model, scaler, target_names):
    """Allow the user to input measurements and predict the species."""
    print("\nEnter the flower measurements:")
    sepal_length = float(input("Sepal Length (cm): "))
    sepal_width = float(input("Sepal Width (cm): "))
    petal_length = float(input("Petal Length (cm): "))
    petal_width = float(input("Petal Width (cm): "))
    
    user_input = np.array([[sepal_length, sepal_width, petal_length, petal_width]])
    user_input_scaled = scaler.transform(user_input)
    prediction = model.predict(user_input_scaled)
    print(f"Predicted Iris species: {prediction[0]}")

def main():
    file_path = "C:/Users/Manasvi/OneDrive/Desktop/Iris.csv"  # Update with actual file path
    
    # Load and preprocess data
    X, y, target_names = load_data(file_path)
    X_scaled, scaler = preprocess_data(X)
    
    # Split data
    X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=42)
    
    # Train model
    model = train_model(X_train, y_train)
    
    # Evaluate model
    evaluate_model(model, X_test, y_test)
    
    # Save model and scaler
    joblib.dump(model, "iris_model.pkl")
    joblib.dump(scaler, "scaler.pkl")
    
    # Predict new data
    predict_species(model, scaler, target_names)
    
if __name__ == "__main__":
    main()


   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa
Model Accuracy: 1.00

Classification Report:
                  precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        10
Iris-versicolor       1.00      1.00      1.00         9
 Iris-virginica       1.00      1.00      1.00        11

       accuracy                           1.00        30
      macro avg       1.00      1.00      1.00        30
   weighted avg       1.00      1.00      1.00        30


Confusion Matrix:
 [[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]

Enter the flower measurements:


Sepal Length (cm):  5.1
Sepal Width (cm):  3.4
Petal Length (cm):  4.1
Petal Width (cm):  .2


Predicted Iris species: Iris-setosa
